version: '3'
services:
  mysql:
    container_name: some-mysql
    image: mysql:5.7
    volumes:
      - ../pliki-zrodlowe-sklepu/mysql-data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: prestashop
    networks:
      - prestashop_network
  prestashop:
    container_name: prestashop
    image: prestashop/prestashop:1.7.8
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - 8080:80
    volumes:
      - ../pliki-zrodlowe-sklepu/my-prestashop:/var/www/html
    environment:
      DB_SERVER: some-mysql
      DB_NAME: prestashop
      DB_USER: root
      DB_PASSWD: admin
      PS_INSTALL_AUTO: 0
      PS_DOMAIN: localhost:8080
    networks:
      - prestashop_network
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - 8081:80
    environment:
      PMA_HOST: some-mysql
      MYSQL_ROOT_PASSWORD: admin
    networks:
      - prestashop_network
networks:
  prestashop_network:
volumes:
  mysql-data:
