<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBsyzfea\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBsyzfea/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerBsyzfea.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerBsyzfea\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerBsyzfea\appDevDebugProjectContainer([
    'container.build_hash' => 'Bsyzfea',
    'container.build_id' => 'e3358878',
    'container.build_time' => 1733073154,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBsyzfea');
