<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9sxocym\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9sxocym/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container9sxocym.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container9sxocym\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container9sxocym\appDevDebugProjectContainer([
    'container.build_hash' => '9sxocym',
    'container.build_id' => '30ac7da2',
    'container.build_time' => 1733020530,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9sxocym');
