<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container70sxbl6\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container70sxbl6/appProdProjectContainer.php') {
    touch(__DIR__.'/Container70sxbl6.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container70sxbl6\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container70sxbl6\appProdProjectContainer([
    'container.build_hash' => '70sxbl6',
    'container.build_id' => 'b3ac7071',
    'container.build_time' => 1732887613,
], __DIR__.\DIRECTORY_SEPARATOR.'Container70sxbl6');
