<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLpkgd0e\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLpkgd0e/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerLpkgd0e.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerLpkgd0e\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerLpkgd0e\appProdProjectContainer([
    'container.build_hash' => 'Lpkgd0e',
    'container.build_id' => 'cbe2e025',
    'container.build_time' => 1730984277,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLpkgd0e');
