<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXcxb3wg\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXcxb3wg/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerXcxb3wg.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerXcxb3wg\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerXcxb3wg\appProdProjectContainer([
    'container.build_hash' => 'Xcxb3wg',
    'container.build_id' => '8033bb88',
    'container.build_time' => 1732913785,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXcxb3wg');
